### ISSUE TITLE
alist 创建文件的路径不一样老哥

### ISSUE THREAD

**Issue by OxYancy** [ShinChven/alist-aria2-pro-docker-compose#1]
alist 创建文件的路径不一样老哥
![image](https://github.com/ShinChven/alist-aria2-pro-docker-compose/assets/16508677/3ebe5952-2d43-488a-a625-139e59bb0b0a)

**Comment by ShinChven** [comment]
是不一样的 这个显示的是 容器内的位置。
你去看看 volume 的映射。
